### ISSUE TITLE
Cannot switch to locale 'nl' for example.

### ISSUE THREAD

**Issue by ghost** [masylum/dialect-http#4]
I can edit 'de', and I could edit 'pt', 'fr', 'es'.
A button for 'nl' does not appear and if I go to /nl/all manually it tells me that:

ERROR

You don't have acces to the locale `nl`

I think I did the configuration right.

**Comment by masylum** [comment]
Can you paste me the configuration?

**Comment by ghost** [comment]
Sure!

``` javascript

exports = {
    title: 'I18n Editor',
    users: [
    {
        username: 'admin',
        password: 'admin'
    }
    ],
    port: 3001,

    dialect: {
    locales: ['nl', 'de'],
    store: {
        mongodb: {
            collection: 'dialect'
        }
    }
    }
}
```

**Comment by ghost** [comment]
any progress yet on this one?

**Comment by masylum** [comment]
Sorry, I had a busy week. 
Update `dialect` and `dialect-http` and modify the dialect-config.js file.
It should have `module.exports` instead of `exports`.

It was wrong on the Readme file, my fault!

**Comment by ghost** [comment]
Thanks! Indeed, that worked!
