### ISSUE TITLE
Actions in category views throw error

### ISSUE THREAD

**Issue by bkw** [masylum/dialect-http#5]
All actions in public/js/global.js assume the navigation/statistics-bar is present and they read the current counts for ok, pending and missing from there by matching numbers in $(h1.bars).
The category views /:locale/ok, /:locale/pending and /:locale/missing do not have these numbers in the heading, so all actions throw a type error while trying to access parts[0].

I don't know what Your plans about the navigation are, but I doubt that using it as a storage model is a sustainable concept. Maybe something like backbone.js would be an option for the client side model?

I'd be glad to help out, but at this stage it too much depends on how you want to structure the application to create a patch.

Anyway nice work and idea!

**Comment by masylum** [comment]
fixed on the latest version
