### ISSUE TITLE
error installing connect-mongodb@1.0.0rc

### ISSUE THREAD

**Issue by Raigen** [masylum/dialect-http#9]
I am having trouble installing dialect-http via npm.

npm ERR! error installing connect-mongodb@1.0.0rc Error: version not found: 0.9.6-4 : mongodb/0.9.6-4

looking at the issues from connect-mongodb I can see, this issue was reported on July 13 and closed at the same day. But when I try to install dialect-http the error occures. Looking at the package.json in 1.0.0rc tag from connect-mongodb, which is in the dependencies of dialect-http, I can see there is still the 0.9.6-4 version of mongodb in the dependencies.

**Comment by masylum** [comment]
I pushed a new package.json to npm to get the latest connect-mongodb, should work now.

**Comment by Raigen** [comment]
work's great now, thanks a lot :)
